[build-system]
requires = ["setuptools",
            "Cython>=0.29",
            "cysignals>=1.7"]
# We need access to the autogen package at build time.
# Hence we declare a custom build backend.
build-backend = "_custom_build_meta"  # just re-exports setuptools.build_meta definitions
backend-path = ["."]

[project]
name = "cypari2"
version = "2.1.4"
description = "A Python interface to the number theory library PARI/GP"
authors = [
    {name = "Luca De Feo, Vincent Delecroix, Jeroen Demeyer, Vincent Klein", email = "sage-devel@googlegroups.com"},
]
dependencies = [
    "cysignals>=1.7",
]
readme = "README.rst"
license = {text = "GNU General Public License, version 2 or later"}
keywords = ["PARI/GP number theory"]

[project.urls]
Homepage = "https://github.com/sagemath/cypari2"
